In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
merged_df=pd.read_csv('/Users/Daniellaviale/Library/CloudStorage/OneDrive-Personal/Dani/Master/Northeastern/Modeling/Project/cleaned_data_1.csv', index_col=False)

In [4]:
merged_df

,store,sale.date,tran.no,tran.type,cashier,size,color,class.desc,sub.class.desc,unit,unit.cost,sale.amt,unit.current.retail,unit.original.retail,gross_margin,cost,product clearance,season,labels
0,19,2019-01-01,15553,S,2,MED,Ivory,Fashion Tops,Button Down,1,9.70,31.49,40.00,40.0,0.691966,9.70,0,Winter,0
1,19,2019-01-01,15555,S,2,SM,FOREST GREEN,Fashion Tops,Blouse,1,8.37,48.00,48.00,48.0,0.825625,8.37,0,Winter,1
2,19,2019-01-01,15557,S,2,MED,Black,Fashion Tops,Blouse,1,9.60,12.75,21.98,40.0,0.247059,9.60,1,Winter,3
3,19,2019-01-01,15557,S,2,MED,Ivory,Fashion Tops,Blouse,1,11.23,16.23,27.98,44.0,0.308071,11.23,1,Winter,3
4,19,2019-01-01,15561,S,2,Extra Small,Ivory,Fashion Tops,Blouse,1,11.23,14.95,27.98,44.0,0.248829,11.23,1,Winter,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55440,27,2019-12-31,28028,S,2,SM,Gray,"Cardigans,Wraps,Sweaters",Pullover Sweater,1,9.28,29.98,29.98,44.0,0.690460,9.28,1,Fall,0
55441,27,2019-12-31,28028,S,2,MED,Blush,"Cardigans,Wraps,Sweaters",Short Cardigans,1,11.33,29.98,29.98,44.0,0.622081,11.33,1,Fall,0
55442,27,2019-12-31,28028,S,2,SM,Gray,"Cardigans,Wraps,Sweaters",Pullover Sweater,1,10.84,44.00,44.00,44.0,0.753636,10.84,0,Fall,1
55443,27,2019-12-31,28032,S,2,LG,Black,Fashion Tops,Blouse,1,8.96,29.19,38.00,38.0,0.693046,8.96,0,Fall,0
55444,27,2019-12-31,28032,S,2,MED,Ivory,Fashion Tops,Blouse,1,11.33,33.81,44.00,44.0,0.664892,11.33,0,Fall,1

In [5]:
merged_df=merged_df.drop(['sale.date', 'tran.no','tran.type', 'cashier','class.desc'],axis=1)

In [6]:
merged_df.head()

,store,size,color,sub.class.desc,unit,unit.cost,sale.amt,unit.current.retail,unit.original.retail,gross_margin,cost,product clearance,season,labels
0,19,MED,Ivory,Button Down,1,9.70,31.49,40.00,40.0,0.691966,9.70,0,Winter,0
1,19,SM,FOREST GREEN,Blouse,1,8.37,48.00,48.00,48.0,0.825625,8.37,0,Winter,1
2,19,MED,Black,Blouse,1,9.60,12.75,21.98,40.0,0.247059,9.60,1,Winter,3
3,19,MED,Ivory,Blouse,1,11.23,16.23,27.98,44.0,0.308071,11.23,1,Winter,3
4,19,Extra Small,Ivory,Blouse,1,11.23,14.95,27.98,44.0,0.248829,11.23,1,Winter,3

In [7]:
# Create dummies for the 'Size' column
size_dummies = pd.get_dummies(merged_df['size'])
merged_df = pd.concat([merged_df, size_dummies], axis=1)
merged_df.drop('size', axis=1, inplace=True)

In [8]:
merged_df = merged_df.rename(columns={'SM': 'size_S', 'Extra Small': 'size_XS', 'LG': 'size_L', 'M/L': 'size_M/L', 'MED': 'size_M', 'S/M': 'size_S/M', 'XL': 'size_XL', 'XXS': 'size_XXS'})

In [9]:
# Create dummies for the 'season' column
season_dummies = pd.get_dummies(merged_df['season'])
merged_df = pd.concat([merged_df, season_dummies], axis=1)
merged_df.drop('season', axis=1, inplace=True)

In [10]:
# Create dummies for the 'sub.class' column
subclass_dummies = pd.get_dummies(merged_df['sub.class.desc'])
merged_df = pd.concat([merged_df, subclass_dummies], axis=1)
merged_df.drop('sub.class.desc', axis=1, inplace=True)

In [11]:
merged_df = merged_df.rename(columns={'Button Down': 'button_down', 'Long Cardigans': 'long_cardigans', 'Long Sleeve Knits': 'long_sleeve_knits', 'Misc Fashion Tops': 'misc_fashion_tops', 'Pullover Sweater': 'pullover_sweater', 'Short Cardigans': 'short_cardigans', 'Short Sleeve Knits': 'short_sleeve_knits', 'Sleeveless Woven Tanks': 'sleeveless_woven_tanks','Sweater Tanks and Tanks': 'sweater_tanks_and_tanks', 'Traditional Cardigan':'traditional_cardigan'})

# Cluster Analysis

In [12]:
df_cluster=merged_df[['unit','sale.amt', 'unit.current.retail', 'unit.original.retail','gross_margin', 'cost']]

In [13]:
df_cluster

,unit,sale.amt,unit.current.retail,unit.original.retail,gross_margin,cost
0,1,31.49,40.00,40.0,0.691966,9.70
1,1,48.00,48.00,48.0,0.825625,8.37
2,1,12.75,21.98,40.0,0.247059,9.60
3,1,16.23,27.98,44.0,0.308071,11.23
4,1,14.95,27.98,44.0,0.248829,11.23
...,...,...,...,...,...,...
55440,1,29.98,29.98,44.0,0.690460,9.28
55441,1,29.98,29.98,44.0,0.622081,11.33
55442,1,44.00,44.00,44.0,0.753636,10.84
55443,1,29.19,38.00,38.0,0.693046,8.96
55444,1,33.81,44.00,44.0,0.664892,11.33

In [14]:
#data scaling
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler() #initialize
scaler.fit(df_cluster)
scaled_df=scaler.transform(df_cluster)

In [15]:
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

In [16]:
#wcv = []
#silk_score = []

#for i in range(2,15):
 #   km = KMeans(n_clusters=i, random_state = 0) #initialize
  #  km.fit(scaled_df) #train: identify clusters

    #Calculating the within cluster variation& silk score
   # wcv.append(km.inertia_) #wcv
    #silk_score.append(silhouette_score(scaled_df, km.labels_)) #Silk_score

In [17]:
#Plotting the wcv
#plt.plot(range(2,15), wcv)
#plt.xlabel('No. of clusters')
#plt.ylabel('Within cluster variation')

In [18]:
#Silk score
#plt.plot(range(2,15), silk_score)
#plt.xlabel('No. of clusters')
#plt.ylabel('Silk score')

In [19]:
#So we can go with 2 clusters, based on the info in the graphs
km2=KMeans(n_clusters=2, random_state=0)#initialize
km2.fit(scaled_df)#train: identify clusters

KMeans(n_clusters=2, random_state=0)

In [20]:
merged_df['labels']=km2.labels_

###interpret the clusters
df_cluster=merged_df.groupby('labels').mean()

In [21]:
df_cluster
pd.set_option('display.max_columns', None)

In [22]:
df_cluster

,store,unit,unit.cost,sale.amt,unit.current.retail,unit.original.retail,gross_margin,cost,product clearance,size_XS,size_L,size_M/L,size_M,No Size,size_S/M,size_S,size_XL,size_XXS,Fall,Spring,Summer,Winter,Blouse,Bodysuits,button_down,Kimono,long_cardigans,long_sleeve_knits,misc_fashion_tops,pullover_sweater,short_cardigans,short_sleeve_knits,sleeveless_woven_tanks,sweater_tanks_and_tanks,Sweatshirt,traditional_cardigan,Vest
labels,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
0,15.381074,1.003566,8.964557,23.752213,32.206209,37.115562,0.549207,8.995898,0.262815,0.127537,0.159022,0.000029,0.310014,0.000029,0.000058,0.306245,0.035486,0.061579,0.260263,0.253566,0.318480,0.167691,0.221327,0.012728,0.108605,0.003798,0.008930,0.085063,0.000058,0.012815,0.001566,0.294735,0.198017,0.043285,0.007451,0.000783,0.000841
1,15.368205,1.003054,10.967013,31.295242,45.198611,47.046342,0.614608,11.000946,0.108529,0.053739,0.179306,0.000907,0.361762,0.000000,0.000716,0.361476,0.028683,0.013411,0.421801,0.223452,0.166325,0.188422,0.169761,0.000000,0.151721,0.015559,0.057462,0.000668,0.000000,0.405765,0.099318,0.002577,0.050208,0.010213,0.022049,0.012122,0.002577

In [23]:
merged_df['labels'].value_counts()

0    34492
1    20953
Name: labels, dtype: int64

In [24]:
cluster_sizes = merged_df.groupby('labels')['store'].nunique()

# Logistic Regression Model

In [25]:
df_logistic = merged_df

In [26]:
print(df_logistic.columns)

Index(['store', 'color', 'unit', 'unit.cost', 'sale.amt',
       'unit.current.retail', 'unit.original.retail', 'gross_margin', 'cost',
       'product clearance', 'labels', 'size_XS', 'size_L', 'size_M/L',
       'size_M', 'No Size', 'size_S/M', 'size_S', 'size_XL', 'size_XXS',
       'Fall', 'Spring', 'Summer', 'Winter', 'Blouse', 'Bodysuits',
       'button_down', 'Kimono', 'long_cardigans', 'long_sleeve_knits',
       'misc_fashion_tops', 'pullover_sweater', 'short_cardigans',
       'short_sleeve_knits', 'sleeveless_woven_tanks',
       'sweater_tanks_and_tanks', 'Sweatshirt', 'traditional_cardigan',
       'Vest'],
      dtype='object')

In [27]:
#Create dummies for the 'store' column
store_dummies = pd.get_dummies(df_logistic['store'])
df_logistic = pd.concat([df_logistic, store_dummies], axis=1)
df_logistic.drop('store', axis=1, inplace=True)

In [28]:
df_logistic = df_logistic.rename(columns={3: 'store_3', 7: 'store_7', 11: 'store_11', 13: 'store_13', 14: 'store_14', 16: 'store_16', 19: 'store_19', 20: 'store_20',21: 'store_21', 27:'store_27'})

In [29]:
#df_logistic['size_m'] = df_logistic['size_M'] + df_logistic['size_S/M']+ df_logistic['size_M/L']
#df_logistic.drop(['size_M', 'size_M/L', 'size_S/M'], axis=1, inplace=True)

In [30]:
df_logistic['others_class'] = df_logistic['Vest']+ df_logistic['Bodysuits']+ df_logistic['Kimono']+ df_logistic['traditional_cardigan']
df_logistic.drop(['Vest', 'Bodysuits', 'Kimono', 'traditional_cardigan'], axis=1, inplace=True)

df_logistic['cardigans'] = df_logistic['long_cardigans']+ df_logistic['short_cardigans']
df_logistic.drop(['long_cardigans', 'short_cardigans'], axis=1, inplace=True)

df_logistic['sweater'] = df_logistic['long_sleeve_knits'] + df_logistic['pullover_sweater']+ df_logistic['Sweatshirt']
df_logistic.drop(['long_sleeve_knits', 'pullover_sweater', 'Sweatshirt'], axis=1, inplace=True)

df_logistic['tanks'] = df_logistic['sleeveless_woven_tanks'] + df_logistic['sweater_tanks_and_tanks'] + df_logistic['short_sleeve_knits']+ df_logistic['misc_fashion_tops']
df_logistic.drop(['sleeveless_woven_tanks', 'sweater_tanks_and_tanks', 'short_sleeve_knits','misc_fashion_tops'], axis=1, inplace=True)

In [31]:
def group_colors(color):
    neutral = ['Ivory', 'White', 'Sand', 'Heather Oat', 'Heather Gray', 'Gray', 'Black', 'Black/White', 'Cinnamon', 'Taupe', 'Natural', 'Tan', 'Charcoal', 'Silver', 'No Color']
    earthy = ['Brick', 'Rust', 'Marigold', 'Moss', 'Olive', 'Dark Olive', 'Amber', 'Mustard', 'Cognac']
    blue = ['Navy', 'Baby Blue', 'Chambray', 'Indigo', 'Cobalt Blue', 'Teal', 'Aqua', 'Turquoise', 'Light Blue']
    green = ['FOREST GREEN', 'Hunter Green', 'Evergreen', 'Pine']
    pink_red = ['Rose', 'Bright Red', 'Coral', 'Fuchsia', 'Raspberry', 'Living Coral', 'Red', 'Deep Moss', 'Dark Rose']
    purple = ['Purple', 'Vintage Purple']
    yellow_orange = ['Sunshine', 'Lemon', 'Orange', 'Tangerine', 'Banana', 'Saffron', 'Adobe', 'Peach', 'Gold', 'Camel', 'Champagne', 'Yellow']
    other = ['Lavender', 'Lite', 'Ink Navy', 'Multi', 'Blush', 'Med', 'Burgundy', 'Neon Coral', 'Brown', 'Emerald', 'Magenta', 'Mauve', 'Dark', 'Topaz', 'Mint', 'Sage', 'Berry']
    
    if color in neutral:
        return 'Neutral'
    elif color in earthy:
        return 'Earthy'
    elif color in blue:
        return 'Blue'
    elif color in green:
        return 'Green'
    elif color in pink_red:
        return 'Pink/Red'
    elif color in purple:
        return 'Purple'
    elif color in yellow_orange:
        return 'Yellow/Orange'
    else:
        return 'Other_Color'

In [32]:
df_logistic['color_group'] = df_logistic['color'].apply(group_colors)

In [33]:
df_logistic['color_group'].value_counts()

Neutral          28562
Other_Color       9745
Blue              5688
Earthy            4246
Pink/Red          3643
Yellow/Orange     2133
Green             1127
Purple             301
Name: color_group, dtype: int64

In [34]:
# Create dummies for the 'color' column
color_dummies = pd.get_dummies(df_logistic['color_group'])
df_logistic = pd.concat([df_logistic, color_dummies], axis=1)
df_logistic.drop('color_group', axis=1, inplace=True)
df_logistic.drop('color', axis=1, inplace=True)

In [35]:
df_logistic.head()

,unit,unit.cost,sale.amt,unit.current.retail,unit.original.retail,gross_margin,cost,product clearance,labels,size_XS,size_L,size_M/L,size_M,No Size,size_S/M,size_S,size_XL,size_XXS,Fall,Spring,Summer,Winter,Blouse,button_down,store_3,store_7,store_11,store_13,store_14,store_16,store_19,store_20,store_21,store_27,others_class,cardigans,sweater,tanks,Blue,Earthy,Green,Neutral,Other_Color,Pink/Red,Purple,Yellow/Orange
0,1,9.70,31.49,40.00,40.0,0.691966,9.70,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
1,1,8.37,48.00,48.00,48.0,0.825625,8.37,0,1,0,0,0,0,0,0,1,0,0,0,0,0,1,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
2,1,9.60,12.75,21.98,40.0,0.247059,9.60,1,0,0,0,0,1,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
3,1,11.23,16.23,27.98,44.0,0.308071,11.23,1,0,0,0,0,1,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
4,1,11.23,14.95,27.98,44.0,0.248829,11.23,1,0,1,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0

In [36]:
#df_logistic[['unit', 'unit.cost', 'sale.amt', 'unit.current.retail', 'unit.original.retail', 'gross_margin', 'cost', 'product clearance']].corr()

In [37]:
#corr_matrix = x.corr()
#print(corr_matrix)

In [38]:
#Using Size_Nosize, Fall, Tanks and Other colors as base categories
x=df_logistic[['gross_margin','size_XXS','size_L','size_M','size_S', 'size_XS','size_XL','size_S/M','size_M/L', 'Spring','Summer','Winter','Blouse','button_down', 'others_class', 'cardigans', 'sweater', 'Blue', 'Earthy', 'Green', 'Other_Color', 'Pink/Red', 'Purple', 'Yellow/Orange']]
y=df_logistic['product clearance']

##train test split
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test= train_test_split(x,y, test_size=0.3, random_state=101)

#Implementing the Log Model
from sklearn.linear_model import LogisticRegression #import
logmodel=LogisticRegression(solver='liblinear') #initialize
logmodel.fit(x_train,y_train)#fit

logmodel.intercept_ #bo
logmodel.coef_ #b1

probabilities=logmodel.predict_proba(x_test)
y_pred=logmodel.predict(x_test)


##evaluate the model using f1-score
from sklearn.metrics import f1_score
f1_score(y_test,y_pred)

0.8028975741239892

In [39]:
from scipy.stats import norm
import numpy as np
# create a DataFrame to store the feature names, coefficients, and p-values
coef_df = pd.DataFrame({'feature': x.columns, 'coefficient': logmodel.coef_[0]})

# calculate the p-values for each coefficient using the normal distribution
coef_df['p-value'] = [2 * (1 - norm.cdf(np.abs(x))) for x in logmodel.coef_[0]]

# print the coefficients, p-values, and significance levels (alpha=0.05) next to the feature names
for idx, row in coef_df.iterrows():
    if row['p-value'] < 0.05:
        signif = '*'
    else:
        signif = ''
    print(f"{row['feature']}: {row['coefficient']:.3f} (p-value={row['p-value']:.3f}{signif})")

gross_margin: -10.964 (p-value=0.000*)
size_XXS: 0.830 (p-value=0.406)
size_L: 0.435 (p-value=0.663)
size_M: 0.310 (p-value=0.757)
size_S: 0.257 (p-value=0.797)
size_XS: 0.459 (p-value=0.646)
size_XL: 0.618 (p-value=0.537)
size_S/M: 0.059 (p-value=0.953)
size_M/L: 0.906 (p-value=0.365)
Spring: 1.159 (p-value=0.247)
Summer: 0.555 (p-value=0.579)
Winter: 0.719 (p-value=0.472)
Blouse: -0.141 (p-value=0.888)
button_down: -0.067 (p-value=0.946)
others_class: -0.307 (p-value=0.759)
cardigans: -0.276 (p-value=0.782)
sweater: -0.893 (p-value=0.372)
Blue: 0.226 (p-value=0.822)
Earthy: -0.007 (p-value=0.995)
Green: 1.331 (p-value=0.183)
Other_Color: 0.067 (p-value=0.947)
Pink/Red: -0.124 (p-value=0.901)
Purple: 0.833 (p-value=0.405)
Yellow/Orange: -0.200 (p-value=0.841)

In [40]:
#Using the confusion matrix
from sklearn.metrics import (accuracy_score, precision_score,recall_score,f1_score
                             ,confusion_matrix)
confusion_mat = pd.DataFrame(confusion_matrix(y_test,y_pred), 
                             index = ['Actual:0', 'Actual:1'],
                             columns = ['Pred:0', 'Pred:1'])

confusion_mat

          Pred:0  Pred:1
Actual:0   13081     124
Actual:1    1046    2383

In [41]:
accuracy_score(y_test,y_pred)

0.9296621377900686

In [42]:
precision_score(y_test,y_pred)

0.950538492221779

In [43]:
recall_score(y_test,y_pred)

0.694954797317002

# Logistic by Cluster

In [44]:
cluster0_df = df_logistic[merged_df['labels'] == 0]

In [45]:
#Using Size_Nosize, Fall, Tanks and Other colors as base categories
x=cluster0_df[['gross_margin','size_XXS','size_L','size_M','size_S', 'size_XS','size_XL','size_S/M','size_M/L', 'Spring','Summer','Winter','Blouse','button_down', 'others_class', 'cardigans', 'sweater', 'Blue', 'Earthy', 'Green', 'Other_Color', 'Pink/Red', 'Purple', 'Yellow/Orange']]
y=cluster0_df['product clearance']

##train test split
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test= train_test_split(x,y, test_size=0.3, random_state=101)

In [46]:
#Implementing the Log Model
from sklearn.linear_model import LogisticRegression #import
logmodel=LogisticRegression(solver='liblinear') #initialize
logmodel.fit(x_train,y_train)#fit

logmodel.intercept_ #bo
logmodel.coef_ #b1

probabilities=logmodel.predict_proba(x_test)
y_pred=logmodel.predict(x_test)


##evaluate the model using f1-score
from sklearn.metrics import f1_score
f1_score(y_test,y_pred)

0.8112933361013079

In [47]:
accuracy_score(y_test,y_pred)

0.912156938538848

In [48]:
precision_score(y_test,y_pred)

0.9425952725518573

In [49]:
recall_score(y_test,y_pred)

0.7120991253644315

In [50]:
from scipy.stats import norm
import numpy as np
# create a DataFrame to store the feature names, coefficients, and p-values
coef_df = pd.DataFrame({'feature': x.columns, 'coefficient': logmodel.coef_[0]})

# calculate the p-values for each coefficient using the normal distribution
coef_df['p-value'] = [2 * (1 - norm.cdf(np.abs(x))) for x in logmodel.coef_[0]]

# print the coefficients, p-values, and significance levels (alpha=0.05) next to the feature names
for idx, row in coef_df.iterrows():
    if row['p-value'] < 0.05:
        signif = '*'
    else:
        signif = ''
    print(f"{row['feature']}: {row['coefficient']:.3f} (p-value={row['p-value']:.3f}{signif})")

gross_margin: -9.733 (p-value=0.000*)
size_XXS: 0.828 (p-value=0.408)
size_L: 0.579 (p-value=0.563)
size_M: 0.469 (p-value=0.639)
size_S: 0.421 (p-value=0.674)
size_XS: 0.614 (p-value=0.539)
size_XL: 0.842 (p-value=0.400)
size_S/M: 0.000 (p-value=1.000)
size_M/L: -0.290 (p-value=0.772)
Spring: 0.633 (p-value=0.526)
Summer: 0.196 (p-value=0.845)
Winter: 0.389 (p-value=0.697)
Blouse: -0.033 (p-value=0.974)
button_down: -0.095 (p-value=0.924)
others_class: -0.426 (p-value=0.670)
cardigans: 1.257 (p-value=0.209)
sweater: -0.868 (p-value=0.385)
Blue: 0.369 (p-value=0.712)
Earthy: -0.029 (p-value=0.977)
Green: 1.081 (p-value=0.280)
Other_Color: 0.267 (p-value=0.789)
Pink/Red: 0.142 (p-value=0.887)
Purple: 0.699 (p-value=0.485)
Yellow/Orange: -0.169 (p-value=0.866)

In [51]:
cluster1_df = df_logistic[df_logistic['labels'] == 1]

In [52]:
#Using Size_Nosize, Fall, Tanks and Other colors as base categories
x=cluster1_df[['gross_margin','size_XXS','size_L','size_M','size_S', 'size_XS','size_XL','size_S/M','size_M/L', 'Spring','Summer','Winter','Blouse','button_down', 'others_class', 'cardigans', 'sweater', 'Blue', 'Earthy', 'Green', 'Other_Color', 'Pink/Red', 'Purple', 'Yellow/Orange']]
y=cluster1_df['product clearance']

##train test split
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test= train_test_split(x,y, test_size=0.3, random_state=101)

#Implementing the Log Model
from sklearn.linear_model import LogisticRegression #import
logmodel=LogisticRegression(solver='liblinear') #initialize
logmodel.fit(x_train,y_train)#fit

logmodel.intercept_ #bo
logmodel.coef_ #b1

probabilities=logmodel.predict_proba(x_test)
y_pred=logmodel.predict(x_test)


##evaluate the model using f1-score
from sklearn.metrics import f1_score
f1_score(y_test,y_pred)

0.8060965283657916

In [53]:
accuracy_score(y_test,y_pred)

0.9635698377346484

In [54]:
precision_score(y_test,y_pred)

0.9388560157790927

In [55]:
recall_score(y_test,y_pred)

0.7062314540059347

In [57]:
from scipy.stats import norm
import numpy as np
# create a DataFrame to store the feature names, coefficients, and p-values
coef_df = pd.DataFrame({'feature': x.columns, 'coefficient': logmodel.coef_[0]})

# calculate the p-values for each coefficient using the normal distribution
coef_df['p-value'] = [2 * (1 - norm.cdf(np.abs(x))) for x in logmodel.coef_[0]]

# print the coefficients, p-values, and significance levels (alpha=0.05) next to the feature names
for idx, row in coef_df.iterrows():
    if row['p-value'] < 0.05:
        signif = '*'
    else:
        signif = ''
    print(f"{row['feature']}: {row['coefficient']:.3f} (p-value={row['p-value']:.3f}{signif})")

gross_margin: -11.914 (p-value=0.000*)
size_XXS: 1.148 (p-value=0.251)
size_L: 0.122 (p-value=0.903)
size_M: -0.049 (p-value=0.961)
size_S: -0.071 (p-value=0.943)
size_XS: 0.042 (p-value=0.966)
size_XL: 0.182 (p-value=0.855)
size_S/M: -0.373 (p-value=0.709)
size_M/L: 0.133 (p-value=0.894)
Spring: 3.482 (p-value=0.000*)
Summer: 0.659 (p-value=0.510)
Winter: 2.369 (p-value=0.018*)
Blouse: 1.194 (p-value=0.233)
button_down: 1.568 (p-value=0.117)
others_class: 1.717 (p-value=0.086)
cardigans: 2.096 (p-value=0.036*)
sweater: 1.900 (p-value=0.057)
Blue: -0.102 (p-value=0.919)
Earthy: -0.303 (p-value=0.762)
Green: 1.792 (p-value=0.073)
Other_Color: -0.183 (p-value=0.855)
Pink/Red: -0.759 (p-value=0.448)
Purple: 0.172 (p-value=0.863)
Yellow/Orange: -0.743 (p-value=0.458)

In [58]:
from scipy.stats import norm
import numpy as np
# create a DataFrame to store the feature names, coefficients, and p-values
coef_df = pd.DataFrame({'feature': x.columns, 'coefficient': logmodel.coef_[0]})

# calculate the p-values for each coefficient using the normal distribution
coef_df['p-value'] = [2 * (1 - norm.cdf(np.abs(x))) for x in logmodel.coef_[0]]

# print the coefficients, p-values, and significance levels (alpha=0.05) next to the feature names
for idx, row in coef_df.iterrows():
    if row['p-value'] < 0.05:
        signif = '*'
    else:
        signif = ''
    print(f"{row['feature']}: {row['coefficient']:.3f} (p-value={row['p-value']:.3f}{signif})")

gross_margin: -11.914 (p-value=0.000*)
size_XXS: 1.148 (p-value=0.251)
size_L: 0.122 (p-value=0.903)
size_M: -0.049 (p-value=0.961)
size_S: -0.071 (p-value=0.943)
size_XS: 0.042 (p-value=0.966)
size_XL: 0.182 (p-value=0.855)
size_S/M: -0.373 (p-value=0.709)
size_M/L: 0.133 (p-value=0.894)
Spring: 3.482 (p-value=0.000*)
Summer: 0.659 (p-value=0.510)
Winter: 2.369 (p-value=0.018*)
Blouse: 1.194 (p-value=0.233)
button_down: 1.568 (p-value=0.117)
others_class: 1.717 (p-value=0.086)
cardigans: 2.096 (p-value=0.036*)
sweater: 1.900 (p-value=0.057)
Blue: -0.102 (p-value=0.919)
Earthy: -0.303 (p-value=0.762)
Green: 1.792 (p-value=0.073)
Other_Color: -0.183 (p-value=0.855)
Pink/Red: -0.759 (p-value=0.448)
Purple: 0.172 (p-value=0.863)
Yellow/Orange: -0.743 (p-value=0.458)

# Additional Models

In [1668]:
cluster0_df = df_logistic[merged_df['labels'] == 0]

In [1669]:
store3_df = cluster0_df[cluster0_df['store_3'] == 1]

In [1671]:
#Using Size_Nosize, Fall, Tanks and Other colors as base categories
x=store3_df[['gross_margin','size_XXS','size_L','size_M','size_S', 'size_XS','size_XL','size_S/M','size_M/L', 'Spring','Summer','Winter','Blouse','button_down', 'others_class', 'cardigans', 'sweater', 'Blue', 'Earthy', 'Green', 'Other_Color', 'Pink/Red', 'Purple', 'Yellow/Orange']]
y=store3_df['product clearance']

##train test split
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test= train_test_split(x,y, test_size=0.3, random_state=101)

In [1672]:
#Implementing the Log Model
from sklearn.linear_model import LogisticRegression #import
logmodel=LogisticRegression(solver='liblinear') #initialize
logmodel.fit(x_train,y_train)#fit

logmodel.intercept_ #bo
logmodel.coef_ #b1

probabilities=logmodel.predict_proba(x_test)
y_pred=logmodel.predict(x_test)


##evaluate the model using f1-score
from sklearn.metrics import f1_score
f1_score(y_test,y_pred)

0.8731942215088282

In [1673]:
from scipy.stats import norm
import numpy as np
# create a DataFrame to store the feature names, coefficients, and p-values
coef_df = pd.DataFrame({'feature': x.columns, 'coefficient': logmodel.coef_[0]})

# calculate the p-values for each coefficient using the normal distribution
coef_df['p-value'] = [2 * (1 - norm.cdf(np.abs(x))) for x in logmodel.coef_[0]]

# print the coefficients, p-values, and significance levels (alpha=0.05) next to the feature names
for idx, row in coef_df.iterrows():
    if row['p-value'] < 0.05:
        signif = '*'
    else:
        signif = ''
    print(f"{row['feature']}: {row['coefficient']:.3f} (p-value={row['p-value']:.3f}{signif})")

gross_margin: -11.374 (p-value=0.000*)
size_XXS: 1.170 (p-value=0.242)
size_L: 0.484 (p-value=0.628)
size_M: 0.528 (p-value=0.597)
size_S: 0.790 (p-value=0.429)
size_XS: 0.830 (p-value=0.407)
size_XL: 0.953 (p-value=0.340)
size_S/M: 0.000 (p-value=1.000)
size_M/L: 0.000 (p-value=1.000)
Spring: 0.490 (p-value=0.624)
Summer: 0.268 (p-value=0.788)
Winter: -0.058 (p-value=0.954)
Blouse: -0.336 (p-value=0.737)
button_down: 0.092 (p-value=0.927)
others_class: 0.250 (p-value=0.803)
cardigans: -0.122 (p-value=0.903)
sweater: -1.376 (p-value=0.169)
Blue: 0.149 (p-value=0.881)
Earthy: -0.215 (p-value=0.830)
Green: 0.205 (p-value=0.838)
Other_Color: 0.109 (p-value=0.913)
Pink/Red: -0.226 (p-value=0.821)
Purple: 0.700 (p-value=0.484)
Yellow/Orange: -0.584 (p-value=0.559)

In [1680]:
df_logistic['store_3_store_11_interaction'] = df_logistic['store_3'] * df_logistic['store_11']

In [1682]:
#Using Size_Nosize, Fall, Tanks and Other colors as base categories
x=df_logistic[['gross_margin','size_XXS','size_L','size_M','size_S', 'size_XS','size_XL','size_S/M','size_M/L', 'Spring','Summer','Winter','Blouse','button_down', 'others_class', 'cardigans', 'sweater', 'Blue', 'Earthy', 'Green', 'Other_Color', 'Pink/Red', 'Purple', 'Yellow/Orange', 'store_3_store_11_interaction', 'store_3', 'store_11' ]]
y=df_logistic['product clearance']

##train test split
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test= train_test_split(x,y, test_size=0.3, random_state=101)

#Implementing the Log Model
from sklearn.linear_model import LogisticRegression #import
logmodel=LogisticRegression(solver='liblinear') #initialize
logmodel.fit(x_train,y_train)#fit

logmodel.intercept_ #bo
logmodel.coef_ #b1

probabilities=logmodel.predict_proba(x_test)
y_pred=logmodel.predict(x_test)


##evaluate the model using f1-score
from sklearn.metrics import f1_score
f1_score(y_test,y_pred)

0.8010779855145695

In [1683]:
from scipy.stats import norm
import numpy as np
# create a DataFrame to store the feature names, coefficients, and p-values
coef_df = pd.DataFrame({'feature': x.columns, 'coefficient': logmodel.coef_[0]})

# calculate the p-values for each coefficient using the normal distribution
coef_df['p-value'] = [2 * (1 - norm.cdf(np.abs(x))) for x in logmodel.coef_[0]]

# print the coefficients, p-values, and significance levels (alpha=0.05) next to the feature names
for idx, row in coef_df.iterrows():
    if row['p-value'] < 0.05:
        signif = '*'
    else:
        signif = ''
    print(f"{row['feature']}: {row['coefficient']:.3f} (p-value={row['p-value']:.3f}{signif})")

gross_margin: -10.928 (p-value=0.000*)
size_XXS: 0.816 (p-value=0.415)
size_L: 0.424 (p-value=0.671)
size_M: 0.295 (p-value=0.768)
size_S: 0.244 (p-value=0.807)
size_XS: 0.447 (p-value=0.655)
size_XL: 0.604 (p-value=0.546)
size_S/M: 0.064 (p-value=0.949)
size_M/L: 0.932 (p-value=0.352)
Spring: 1.167 (p-value=0.243)
Summer: 0.558 (p-value=0.577)
Winter: 0.727 (p-value=0.467)
Blouse: -0.146 (p-value=0.884)
button_down: -0.070 (p-value=0.945)
others_class: -0.316 (p-value=0.752)
cardigans: -0.267 (p-value=0.789)
sweater: -0.888 (p-value=0.375)
Blue: 0.225 (p-value=0.822)
Earthy: -0.011 (p-value=0.991)
Green: 1.324 (p-value=0.185)
Other_Color: 0.069 (p-value=0.945)
Pink/Red: -0.127 (p-value=0.899)
Purple: 0.831 (p-value=0.406)
Yellow/Orange: -0.208 (p-value=0.835)
store_3_store_11_interaction: 0.000 (p-value=1.000)
store_3: 0.353 (p-value=0.724)
store_11: 0.083 (p-value=0.934)

In [1684]:
df_logistic['store_16_store_21_interaction'] = df_logistic['store_16'] * df_logistic['store_21']

In [1685]:
#Using Size_Nosize, Fall, Tanks and Other colors as base categories
x=df_logistic[['gross_margin','size_XXS','size_L','size_M','size_S', 'size_XS','size_XL','size_S/M','size_M/L', 'Spring','Summer','Winter','Blouse','button_down', 'others_class', 'cardigans', 'sweater', 'Blue', 'Earthy', 'Green', 'Other_Color', 'Pink/Red', 'Purple', 'Yellow/Orange', 'store_16_store_21_interaction', 'store_16', 'store_21' ]]
y=df_logistic['product clearance']

##train test split
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test= train_test_split(x,y, test_size=0.3, random_state=101)

In [1686]:
#Implementing the Log Model
from sklearn.linear_model import LogisticRegression #import
logmodel=LogisticRegression(solver='liblinear') #initialize
logmodel.fit(x_train,y_train)#fit

logmodel.intercept_ #bo
logmodel.coef_ #b1

probabilities=logmodel.predict_proba(x_test)
y_pred=logmodel.predict(x_test)


##evaluate the model using f1-score
from sklearn.metrics import f1_score
f1_score(y_test,y_pred)

0.8055135316859976

In [1687]:
from scipy.stats import norm
import numpy as np
# create a DataFrame to store the feature names, coefficients, and p-values
coef_df = pd.DataFrame({'feature': x.columns, 'coefficient': logmodel.coef_[0]})

# calculate the p-values for each coefficient using the normal distribution
coef_df['p-value'] = [2 * (1 - norm.cdf(np.abs(x))) for x in logmodel.coef_[0]]

# print the coefficients, p-values, and significance levels (alpha=0.05) next to the feature names
for idx, row in coef_df.iterrows():
    if row['p-value'] < 0.05:
        signif = '*'
    else:
        signif = ''
    print(f"{row['feature']}: {row['coefficient']:.3f} (p-value={row['p-value']:.3f}{signif})")

gross_margin: -10.937 (p-value=0.000*)
size_XXS: 0.835 (p-value=0.404)
size_L: 0.444 (p-value=0.657)
size_M: 0.321 (p-value=0.748)
size_S: 0.265 (p-value=0.791)
size_XS: 0.464 (p-value=0.643)
size_XL: 0.626 (p-value=0.531)
size_S/M: 0.053 (p-value=0.958)
size_M/L: 0.933 (p-value=0.351)
Spring: 1.145 (p-value=0.252)
Summer: 0.534 (p-value=0.594)
Winter: 0.709 (p-value=0.478)
Blouse: -0.151 (p-value=0.880)
button_down: -0.055 (p-value=0.957)
others_class: -0.288 (p-value=0.773)
cardigans: -0.274 (p-value=0.784)
sweater: -0.889 (p-value=0.374)
Blue: 0.228 (p-value=0.819)
Earthy: -0.015 (p-value=0.988)
Green: 1.360 (p-value=0.174)
Other_Color: 0.075 (p-value=0.940)
Pink/Red: -0.109 (p-value=0.913)
Purple: 0.873 (p-value=0.383)
Yellow/Orange: -0.205 (p-value=0.838)
store_16_store_21_interaction: 0.000 (p-value=1.000)
store_16: -0.153 (p-value=0.878)
store_21: -0.857 (p-value=0.391)

In [61]:
store3_df = df_logistic[df_logistic['store_3'] == 1]

In [62]:
x=store3_df[['gross_margin','size_XXS','size_L','size_M','size_S', 'size_XS','size_XL','size_S/M','size_M/L', 'Spring','Summer','Winter','Blouse','button_down', 'others_class', 'cardigans', 'sweater', 'Blue', 'Earthy', 'Green', 'Other_Color', 'Pink/Red', 'Purple', 'Yellow/Orange', 'store_3']]
y=store3_df['product clearance']

##train test split
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test= train_test_split(x,y, test_size=0.3, random_state=101)

#Implementing the Log Model
from sklearn.linear_model import LogisticRegression #import
logmodel=LogisticRegression(solver='liblinear') #initialize
logmodel.fit(x_train,y_train)#fit

logmodel.intercept_ #bo
logmodel.coef_ #b1

probabilities=logmodel.predict_proba(x_test)
y_pred=logmodel.predict(x_test)


##evaluate the model using f1-score
from sklearn.metrics import f1_score
f1_score(y_test,y_pred)

0.8463611859838276

In [63]:
from scipy.stats import norm
import numpy as np
# create a DataFrame to store the feature names, coefficients, and p-values
coef_df = pd.DataFrame({'feature': x.columns, 'coefficient': logmodel.coef_[0]})

# calculate the p-values for each coefficient using the normal distribution
coef_df['p-value'] = [2 * (1 - norm.cdf(np.abs(x))) for x in logmodel.coef_[0]]

# print the coefficients, p-values, and significance levels (alpha=0.05) next to the feature names
for idx, row in coef_df.iterrows():
    if row['p-value'] < 0.05:
        signif = '*'
    else:
        signif = ''
    print(f"{row['feature']}: {row['coefficient']:.3f} (p-value={row['p-value']:.3f}{signif})")

gross_margin: -12.509 (p-value=0.000*)
size_XXS: 0.982 (p-value=0.326)
size_L: 0.062 (p-value=0.951)
size_M: 0.239 (p-value=0.811)
size_S: 0.461 (p-value=0.645)
size_XS: 0.410 (p-value=0.682)
size_XL: 0.540 (p-value=0.589)
size_S/M: 0.000 (p-value=1.000)
size_M/L: 0.000 (p-value=1.000)
Spring: 1.047 (p-value=0.295)
Summer: 0.594 (p-value=0.552)
Winter: 0.491 (p-value=0.623)
Blouse: -0.435 (p-value=0.663)
button_down: 0.131 (p-value=0.896)
others_class: -0.367 (p-value=0.714)
cardigans: -0.679 (p-value=0.497)
sweater: -1.207 (p-value=0.228)
Blue: -0.164 (p-value=0.870)
Earthy: -0.093 (p-value=0.926)
Green: 0.549 (p-value=0.583)
Other_Color: -0.317 (p-value=0.752)
Pink/Red: -0.503 (p-value=0.615)
Purple: -0.189 (p-value=0.850)
Yellow/Orange: -0.884 (p-value=0.377)
store_3: 2.693 (p-value=0.007*)

In [71]:
df_logistic['store_3_summer'] = df_logistic['store_3'] * df_logistic['Summer']

In [72]:
x=df_logistic[['gross_margin','size_XXS','size_L','size_M','size_S', 'size_XS','size_XL','size_S/M','size_M/L', 'Spring','Summer','Winter','Blouse','button_down', 'others_class', 'cardigans', 'sweater', 'Blue', 'Earthy', 'Green', 'Other_Color', 'Pink/Red', 'Purple', 'Yellow/Orange', 'store_3', 'store_3_summer']]
y=df_logistic['product clearance']

##train test split
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test= train_test_split(x,y, test_size=0.3, random_state=101)

#Implementing the Log Model
from sklearn.linear_model import LogisticRegression #import
logmodel=LogisticRegression(solver='liblinear') #initialize
logmodel.fit(x_train,y_train)#fit

logmodel.intercept_ #bo
logmodel.coef_ #b1

probabilities=logmodel.predict_proba(x_test)
y_pred=logmodel.predict(x_test)


##evaluate the model using f1-score
from sklearn.metrics import f1_score
f1_score(y_test,y_pred)

0.8010118043844857

In [73]:
from scipy.stats import norm
import numpy as np
# create a DataFrame to store the feature names, coefficients, and p-values
coef_df = pd.DataFrame({'feature': x.columns, 'coefficient': logmodel.coef_[0]})

# calculate the p-values for each coefficient using the normal distribution
coef_df['p-value'] = [2 * (1 - norm.cdf(np.abs(x))) for x in logmodel.coef_[0]]

# print the coefficients, p-values, and significance levels (alpha=0.05) next to the feature names
for idx, row in coef_df.iterrows():
    if row['p-value'] < 0.05:
        signif = '*'
    else:
        signif = ''
    print(f"{row['feature']}: {row['coefficient']:.3f} (p-value={row['p-value']:.3f}{signif})")

gross_margin: -10.926 (p-value=0.000*)
size_XXS: 0.820 (p-value=0.412)
size_L: 0.428 (p-value=0.669)
size_M: 0.300 (p-value=0.764)
size_S: 0.249 (p-value=0.803)
size_XS: 0.453 (p-value=0.650)
size_XL: 0.608 (p-value=0.543)
size_S/M: 0.063 (p-value=0.950)
size_M/L: 0.910 (p-value=0.363)
Spring: 1.166 (p-value=0.244)
Summer: 0.539 (p-value=0.590)
Winter: 0.724 (p-value=0.469)
Blouse: -0.143 (p-value=0.886)
button_down: -0.069 (p-value=0.945)
others_class: -0.312 (p-value=0.755)
cardigans: -0.264 (p-value=0.792)
sweater: -0.885 (p-value=0.376)
Blue: 0.225 (p-value=0.822)
Earthy: -0.012 (p-value=0.990)
Green: 1.325 (p-value=0.185)
Other_Color: 0.069 (p-value=0.945)
Pink/Red: -0.129 (p-value=0.897)
Purple: 0.830 (p-value=0.406)
Yellow/Orange: -0.210 (p-value=0.834)
store_3: 0.302 (p-value=0.763)
store_3_summer: 0.189 (p-value=0.850)